= Spring Boot Enterprise
:Spring-docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference
:github: https://github.com/gleasonsean/spring-boot-enterprise
:maven-bom: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms
:spring-boot-dependencies: https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-dependencies

The Spring Boot approach to building enterprise libraries at your company.
By building on the same principals as the {Spring-docs}\html[Spring Boot Project], you too can build auto-configuration and
{maven-bom}[Bills of Material] for your company with minimum fuss.

Both Maven and Gradle are supported.  Follow the 'Installation and Getting Started' for your respective build tool to get setup.

== Installation and Getting Started

WARNING: Refrain from loading this project in an IDE like Intellij/Eclipse until after running the setup scripts.

=== Maven

1)  After forking this repository, remove all unneeded gradle files by running the below script.
[source,bash,indent=0]
----
rm -rf ./gradle &&\
rm -rf ./buildSrc &&\
rm -rf ./.gradle &&\
rm -rf ./*.gradle &&\
rm -rf ./**/*.gradle* &&\
rm -rf ./gradle*

----

2)  Update 'COMPANY_NAME' below and run the following script to rename 'enterprise' to your companies name.
[source,bash,indent=0]
----
COMPANY_NAME=Gleason &&\

COMPANY_NAME_LOWER=$(echo "${COMPANY_NAME}" |awk '{print tolower($0)}') &&\
find . -type f -name "*pom.xml" -exec sed -i '' 's/-enterprise/-'"${COMPANY_NAME_LOWER}"'/g' {} + &&\
find . -type f -name "*pom.xml" -exec sed -i '' 's/Spring Boot Enterprise/Spring Boot '"${COMPANY_NAME}"'/g' {} + &&\
find . -type f -name "*pom.xml" -exec sed -i '' 's/com.enterprise/ '"com.${COMPANY_NAME_LOWER}"'/g' {} + &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-enterprise-starter  ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-${COMPANY_NAME_LOWER}-starter &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-enterprise-starter-parent  ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-${COMPANY_NAME_LOWER}-starter-parent &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-starters  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-starters &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER} &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-autoconfigure  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-autoconfigure &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-dependencies  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-dependencies &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-parent  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-parent &&\
mv -f ./spring-boot-enterprise-project  ./spring-boot-${COMPANY_NAME_LOWER}-project &&\
mv -f ../spring-boot-enterprise  ../spring-boot-${COMPANY_NAME_LOWER}

----
3) Load the renamed project in your favorite IDE.


=== Gradle

1)  After forking this repository, remove all unneeded maven files by running the below script.
[source,bash,indent=0]
----
rm -rf ./.mvn &&\
rm -rf ./mvn* &&\
rm -rf ./**/spring-boot-enterprise-*parent &&\
rm -rf ./**/*pom.xml

----

2)  Update 'COMPANY_NAME' below and run the following script to rename 'enterprise' to your companies name.
[source,bash,indent=0]
----
COMPANY_NAME=Gleason &&\

COMPANY_NAME_LOWER=$(echo "${COMPANY_NAME}" |awk '{print tolower($0)}') &&\
find . -type f -name "*.gradle" -exec sed -i '' 's/-enterprise/-'"${COMPANY_NAME_LOWER}"'/g' {} + &&\
find . -type f -name "*.gradle" -exec sed -i '' 's/Spring Boot Enterprise/Spring Boot '"${COMPANY_NAME}"'/g' {} + &&\
find . -type f -name "*.gradle" -exec sed -i '' 's/com.enterprise/ '"com.${COMPANY_NAME_LOWER}"'/g' {} + &&\
find . -type f -name "*.java" -exec sed -i '' 's/com.enterprise/ '"com.${COMPANY_NAME_LOWER}"'/g' {} + &&\
mv -f ./buildSrc/src/main/java/com/enterprise  ./buildSrc/src/main/java/com/${COMPANY_NAME_LOWER} &&\
./gradlew -p buildSrc format &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-enterprise-starter  ./spring-boot-enterprise-project/spring-boot-enterprise-starters/spring-boot-${COMPANY_NAME_LOWER}-starter &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-starters  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-starters &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER} &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-autoconfigure  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-autoconfigure &&\
mv -f ./spring-boot-enterprise-project/spring-boot-enterprise-dependencies  ./spring-boot-enterprise-project/spring-boot-${COMPANY_NAME_LOWER}-dependencies &&\
mv -f ./spring-boot-enterprise-project  ./spring-boot-${COMPANY_NAME_LOWER}-project &&\
mv -f ../spring-boot-enterprise  ../spring-boot-${COMPANY_NAME_LOWER}


----
3) Load the renamed project in your favorite IDE.


== Usage

=== Maven
[source,xml,indent=0]
----
<!-- Inherit defaults from Spring Boot -->
<parent>
    <groupId>com.enterprise</groupId>
    <artifactId>spring-boot-enterprise-starter-parent</artifactId>
    <version>${LATEST}</version>
</parent>
----

== Modules

There are several modules in Spring Boot Enterprise.
Here is a quick overview:

=== spring-boot-enterprise

The main library providing features that support the other parts of Spring Boot.

=== spring-boot-enterprise-autoconfigure

Spring Boot Enterprise can configure large parts of typical applications based on the content of their classpath.
Since it uses Spring Boot underneath the covers, a single `@EnableAutoConfiguration` annotation triggers auto-configuration of the Spring context.

Auto-configuration attempts to deduce which beans a user might need.
Auto-configuration will always back away as the user starts to define their own beans.

=== spring-boot-enterprise-dependencies

Provides a {maven-bom}[Bill of Materials] for the entire Spring Boot Enterprise project.  This project extends the
{spring-boot-dependencies}[Spring Boot Dependencies BOM] to allow for custom libraries to be built with a compatability
in mind by locking in an assigned Spring Boot version.
