= Spring Boot Enterprise
:Spring-docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference
:github: https://github.com/gleasonsean/spring-boot-enterprise
:maven-bom: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms
:spring-boot-dependencies: https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-dependencies

The Spring Boot approach to building enterprise libraries at your company.
By building on the same principals as the {Spring-docs}\html[Spring Boot Project], you too can build auto-configuration and
{maven-bom}[Bills of Material] for your company with minimum fuss.

== Installation and Getting Started
Simply fork this repository and perform the following:

TODO

The Spring Boot {Spring-docs}/html/[reference documentation] already includes detailed {Spring-docs}/html/getting-started.html#getting-started-installing-spring-boot[installation instructions] as well as a comprehensive {Spring-docs}/html/getting-started.html#getting-started-first-application[``getting started``] guide.

== Modules

There are several modules in Spring Boot Enterprise.
Here is a quick overview:

=== spring-boot-enterprise

The main library providing features that support the other parts of Spring Boot.

=== spring-boot-enterprise-autoconfigure

Spring Boot Enterprise can configure large parts of typical applications based on the content of their classpath.
Since it uses Spring Boot underneath the covers, a single `@EnableAutoConfiguration` annotation triggers auto-configuration of the Spring context.

Auto-configuration attempts to deduce which beans a user might need.
Auto-configuration will always back away as the user starts to define their own beans.

=== spring-boot-enterprise-dependencies

Provides a {maven-bom}[Bill of Materials] for the entire Spring Boot Enterprise project.  This project extends the
{spring-boot-dependencies}[Spring Boot Dependencies BOM] to allow for custom libraries to be built with a compatability
in mind by locking in an assigned Spring Boot version.
